# Funding options for BotLog Protocol
# Uncomment and update with your actual usernames/links

# GitHub Sponsors
# github: KullAxel

# Polar.sh (for bounty payouts)
# custom: ["https://polar.sh/KullAxel"]

# Alternative funding platforms
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username

# Direct crypto donations (optional)
# custom: ["https://your-crypto-donation-page.com"]
